FROM ruby:2.7.1-alpine

# Install system dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
# Set the working directory

RUN mkdir /reddit-clone-rails
WORKDIR /reddit-clone-rails

# Copy over Gemfile and Gemfile.lock
COPY Gemfile Gemfile.lock ./

# Install gems
RUN bundle install

# Copy over the rest of the application code
COPY . .

# Precompile assets
RUN rake assets:precompile

# Expose the port that your application runs on
EXPOSE 3000

# Start the application
CMD ["rails", "server", "-b", "0.0.0.0"]
